src/controllers/admincontroller.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash, Response, abort, send_from_directory, send_file
from jinja2 import TemplateNotFound
from flask_bcrypt import generate_password_hash
import os, sys, threading, time
from classes.AIACast import FFmpegCommandWithTimeLimit
from classes.AIARemake import TransformToExe
from classes.Pyinst import PyToExeConverter
from classes.getIP import NetworkUtils
from pathlib import Path

sys.path.insert(1, "/".join(os.path.realpath(__file__).split("/")[0:-2]))
from src.models.User import User
from src.models.Ticket import Ticket


adminctrl = Blueprint('admin', __name__)
user = User()
tickets = Ticket()
host_ip = NetworkUtils.get_local_ip()
ffmpeg = FFmpegCommandWithTimeLimit()
tranform = TransformToExe()
installer = PyToExeConverter('esharexe22.py')

destination_path = Path(f'./storage/scriptingexe/esharexe22.exe')
                


#Routing to the User upload page page for both GET and POST
@adminctrl.route('', methods=['GET'])
def access_page():
    if 'username' in session:
        the_user = user.find_data(session['username'])
        return render_template('admin/index.html', user = the_user)
    else:
        return redirect(url_for('login.login_GET'))  

        
@adminctrl.route('', methods=['POST'])
def access_page_post():

    #checking if session exists
    if 'username' in session:
        #to ensure if it is admin or not
        if request.form['to_check'] == 'admin':
            #to determin which button was clicked
            if request.form['btn'] == "savebtn":

                if request.form['pin'] == "" or request.form['timer'] == "0":
                    #validating the form
                    flash('Generate a ticket!/Set timer', 'error')
                    return redirect(url_for('admin.access_page'))
                
                else:
                    #save ticket and timer to data.json
                    ticket = tickets.fmt(request.form['pin'], 
                                         request.form['timer'])
                    ticket = tickets.create(ticket)
                    
                    #appending the host ip with the ticket to create a socket
                    #and using udp protocol to recieve frame
                    udpip = f"udp://{host_ip}:{request.form['pin']}"
                    ff = ffmpeg.exe_command_to_recieve(request.form['timer'], 
                                                       udpip)                    
                    flash(f"{ff}", 'success')
                    return redirect(url_for('admin.access_page'))
                
            elif request.form['btn'] == "startbtn":
                if host_ip == "10.0.0.1741gvdg":
                    #if client is host, screen share should not execute
                    flash("This is the host! (session cannot be enabled!)")
                    return redirect(url_for('admin.access_page'))
                    exit()
                
                #ffplay listens on port 5555 anytime the admin wants to share
                udpip = f"udp://{host_ip}:4444"
                timers = "5"

                msg = tranform.copy_file()
                if msg != 'successful':                   
                        flash('There is an issue, (contact Admin)', 'error')
                        return redirect(url_for('admin.access_page'))
                        exit()
                    
                tranform.alter_file(timers, udpip)                    
                try:
                    t1 = threading.Thread(target=installer.convert, 
                                              args=(True, True))
                    t1.start()
                    #to give pyinstaller time to deploy the script to exe
                    time.sleep(12)
                    t1.join()

                    #enable the host to listen to udp @1234
                    ff = ffmpeg.exe_command_to_recieve(timers, 
                                                       udpip) 
                    
                    return send_file(destination_path, as_attachment=True)
                except Exception as e:
                    abort(404, description="Resource not found")

            else:
                #kill the ffplay process
                ffmpeg.killer()
                #ffmpeg.killer_client()
                flash(f'Process Killed!', 'success')                
                return redirect(url_for('admin.access_page'))
            
        else:            
            #check for ip
            if host_ip == None:
                flash('Network connection issue!', 'warning')
                return redirect(url_for('admin.access_page'))
                exit()
            
            if request.form['btn'] == 'startbtn':
                ticket = tickets.find_data(request.form['pin'])

                if ticket == None:

                    flash('That token is unavailable!', 'warning')
                    return redirect(url_for('admin.access_page'))
                else:
                    msg = tranform.copy_file()
                    if msg != 'successful':                   
                        flash('There is an issue, (contact Admin)', 'error')
                        return redirect(url_for('admin.access_page'))
                        exit()
                    
                    udpip = f"udp://{host_ip}:{request.form['pin']}"
                    tranform.alter_file(ticket['timer'], udpip)

                    
                    try:
                        t1 = threading.Thread(target=installer.convert, 
                                              args=(True, True))
                        t1.start()
                        #to give pyinstaller time to deploy the script to .exe
                        time.sleep(12)
                        t1.join()

                        ticket = tickets.delete_data(request.form['pin'])

                        return send_file(destination_path, as_attachment=True)
                    except Exception as e:
                        abort(404, description="Resource not found")

            else:
                 try:
                     ffmpeg.killer()
                     flash(f'Process Killed! Close the exe2 file', 'success')
                     return redirect(url_for('admin.access_page'))
                 except FileNotFoundError:            
                    abort(404, description="Resource not found")
                
                
            
    else:
        return redirect(url_for('login.login_GET'))




@adminctrl.route('/user')
def user_page():
    if 'username' in session:
        admin = user.find_data(session['username'])
        #not grant permission for ordinary user
        if admin['role'].lower() != 'admin':
            flash("Permission denied!", "error")
            return redirect(url_for('admin.access_page'))
            exit()        
        
        all_user = user.get_data()
        return render_template('admin/user.html', user = admin, 
                               others = all_user)
    else:
        return redirect(url_for('login.login_GET'))


@adminctrl.route('/add', methods=['GET'])
def add_user():
    if 'username' in session:
        the_user = user.find_data(session['username'])
        return render_template('admin/useradd.html', user = the_user)
    else:
        return redirect(url_for('login.login_GET'))
    

@adminctrl.route('/add', methods=['POST'])
def add_user_post():
    
    password = generate_password_hash(request.form['password']).decode('utf-8')

    dictn ={request.form['Username'] : {
       "Firstname": request.form['Firstname'],
        "Lastname": request.form['Lastname'],
        "sex": request.form['gender'],
        "password": password,
        "role": request.form['role']
    }}

    msg = user.create(dictn)
    flash(msg, 'success')
    return redirect(url_for('admin.add_user'))


@adminctrl.route('/delete')
def delete_user():
    if 'username' in session:
        admin = user.find_data(session['username'])
        if admin['role'].lower() != 'admin':
            flash("Permission denied!", "error")
            return redirect(url_for('admin.access_page'))
            exit()

        usrn = request.args.get('id')
        if session['username'] == usrn:
            flash("Permission denied", "error")
            return redirect(url_for('admin.user_page'))
            exit()

        del_user = user.delete_data(usrn)
        flash(del_user[1], del_user[0])
        return redirect(url_for('admin.user_page'))
    else:
        return redirect(url_for('login.login_GET'))


#Routing to the User upload page page for both GET and POST
@adminctrl.route('/manual')
def manual():
    if 'username' in session:
        the_user = user.find_data(session['username'])
        return render_template('admin/manual.html', user = the_user)
    else:
        return redirect(url_for('login.login_GET'))


#Routing for downloading .exe file
@adminctrl.route('/downloadffmpeg')
def download_ffmpeg():
    ffmpeg_download = Path(f'./storage/scripting/ffmpeg-git-full.7z')
    return send_file(ffmpeg_download, as_attachment=True)





    

templates/layout/adminlayout.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} - My Webpage</title>
    {% endblock %}

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <link rel="icon" type="image/x-icon" href="../static/image/AIA-logo.png">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="../static/css/all.min.css">
  <!-- Ekko Lightbox -->
  <link rel="stylesheet" href="../static/css/ekko-lightbox.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="../static/css/adminlte.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="../static/css/OverlayScrollbars.min.css">
  <!-- toastr -->
  <link rel="stylesheet" href="../static/css/toastr.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    {% block ForNav %}{% endblock %}


<!-- jQuery -->
<script src="../static/js/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="../static/js/bootstrap.bundle.min.js"></script>
<!-- Ekko Lightbox -->
<script src="../static/js/ekko-lightbox.min.js"></script>
<!-- overlayScrollbars -->
<script src="../static/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="../static/js/adminlte.min.js"></script>
<!-- Filterizr-->
<script src="../static/js/jquery.filterizr.min.js"></script>
<!-- Toastr for alert-->
<script src="../static/js/toastr.min.js"></script>
<script>
$(document).ready(function(){
// Get Flash messages from Flask
const messages = '{{ get_flashed_messages(with_categories=true) | tojson }}';
            
            var newmessages = JSON.parse(messages)
                    // Display Toastr notifications from Flash
                    newmessages.forEach(function(message) {
                        const category = message[0];
                        const text = message[1];
                        
                        if (category === 'success') {
                            toastr.success(text, 'Success');
                        } else if (category === 'error') {
                            toastr.error(text, 'Error');
                        } else if (category === 'warning') {
                            toastr.warning(text, 'Warning');
                        } else if (category === 'info') {
                            toastr.info(text, 'Info');
                        }
                      });
            });
</script>
{% block scripting %}{% endblock %}
</body>
</html>

templates/layout/navadmin.html
{% extends "layout/adminlayout.html" %}


{% block ForNav %}

<div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{{url_for('admin.access_page')}}" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{{url_for('admin.manual')}}" class="nav-link">Manual</a>
        </li>
      </ul>
  
      <!-- Right navbar links -->
      <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
          <a class="nav-link" data-widget="navbar-search" href="#" role="button">
            <i class="fas fa-search"></i>
          </a>
          <div class="navbar-search-block">
            <form class="form-inline">
              <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                  <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                  </button>
                  <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                    <i class="fas fa-times"></i>
                  </button>
                </div>
              </div>
            </form>
          </div>
        </li>
        
      </ul>
    </nav>
    <!-- /.navbar -->
  
    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
      <!-- Brand Logo -->
      <a href="../index3.html" class="brand-link">
        <img src="../static/image/AIA-ICON_32X32.ico" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">AIA-CAST</span>
      </a>
  
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
          <div class="info">
            <a href="#" class="d-block">{{user['Firstname']+" "+user['Lastname']}}</a>
          </div>
        </div>
  
        <!-- SidebarSearch Form -->
        <div class="form-inline">
          <div class="input-group" data-widget="sidebar-search">
            <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
              <button class="btn btn-sidebar">
                <i class="fas fa-search fa-fw"></i>
              </button>
            </div>
          </div>
        </div>
  
        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                 with font-awesome or any other icon font library -->
            <li class="nav-item">
              <a href="{{url_for('admin.access_page')}}" class="nav-link">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                  Dashboard
                </p>
              </a>
              <a href="{{url_for('admin.user_page')}}" class="nav-link">
                <i class="nav-icon fas fa-users"></i>
                <p>
                  Manage User
                </p>
              </a>
            </li>
          </ul>
        </nav>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    
    {% block content %}{% endblock %}
    <footer class="main-footer">
      <div class="float-right d-none d-sm-block">
        <b>Version</b> 3.2.0
      </div>
      <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
    </footer>
  
    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
  </div>
  <!-- ./wrapper -->



{% endblock %}